allowBuilds:
  next: set this to true or false
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - next@16.0.7
  - next@16.0.9
  - next@16.1.5
  - next@16.0.11
  - js-yaml@4.1.1
  - minimatch@3.1.3
  - minimatch@9.0.6
  - minimatch@9.0.7
  - minimatch@3.1.4
  - ajv@6.14.0
  - flatted@3.4.0
  - next@16.1.7
  - flatted@3.4.2
  - brace-expansion@1.1.13
  - brace-expansion@2.0.3
  - picomatch@2.3.2
  - picomatch@4.0.4
  - next@16.2.3
  - postcss@8.5.10
  - next@16.2.5
  - next@16.2.6
